---
output: rmarkdown::github_document
editor_options: 
  chunk_output_type: console
---
```{r pkg-knitr-opts, include=FALSE}
hrbrpkghelpr::global_opts()
```

```{r badges, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::stinking_badges()
```

```{r description, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::yank_title_and_description()
```

## What's Inside The Tin

The following functions are implemented:

```{r ingredients, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::describe_ingredients()
```

## Installation

```{r install-ex, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::install_block()
```

## Usage

```{r lib-ex}
library(daybreak)

# current version
packageVersion("daybreak")

```

Near me:

```{r ex1}
day_length("2019-12-31", -70.8636, 43.2683)
day_civil_twilight_length("2019-12-31", -70.8636, 43.2683)
day_nautical_twilight_length("2019-12-31", -70.8636, 43.2683)
day_astronomical_twilight_length("2019-12-31", -70.8636, 43.2683)
sun_rise_set("2019-12-31", -70.8636, 43.2683)
civil_twilight("2019-12-31", -70.8636, 43.2683)
nautical_twilight("2019-12-31", -70.8636, 43.2683)
astronomical_twilight("2019-12-31", -70.8636, 43.2683)
```

Tromsø, Norway (Winter)

```{r ex2}
day_length("2019-12-31", 18.9553, 69.6492)
day_civil_twilight_length("2019-12-31", 18.9553, 69.6492)
day_nautical_twilight_length("2019-12-31", 18.9553, 69.6492)
day_astronomical_twilight_length("2019-12-31", 18.9553, 69.6492)
sun_rise_set("2019-12-31", 18.9553, 69.6492)
civil_twilight("2019-12-31", 18.9553, 69.6492)
nautical_twilight("2019-12-31", 18.9553, 69.6492)
astronomical_twilight("2019-12-31", 18.9553, 69.6492)
```

Tromsø, Norway (Summer)

```{r ex3}
day_length("2019-06-01", 18.9553, 69.6492)
day_civil_twilight_length("2019-06-01", 18.9553, 69.6492)
day_nautical_twilight_length("2019-06-01", 18.9553, 69.6492)
day_astronomical_twilight_length("2019-06-01", 18.9553, 69.6492)
sun_rise_set("2019-06-01", 18.9553, 69.6492)
civil_twilight("2019-06-01", 18.9553, 69.6492)
nautical_twilight("2019-06-01", 18.9553, 69.6492)
astronomical_twilight("2019-06-01", 18.9553, 69.6492)
```

## daybreak Metrics

```{r cloc, echo=FALSE}
cloc::cloc_pkg_md()
```

## Code of Conduct

Please note that this project is released with a Contributor Code of Conduct. 
By participating in this project you agree to abide by its terms.
